---
- name: Open firewall for HTTP
  firewalld:
    port: "80/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- name: Add Nginx repository
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes

- name: Install Nginx
  yum:
    name: nginx

- name: Delete default configuration
  file:
    state: absent
    path: /etc/nginx/conf.d/default.conf

- name: Deploy config file
  template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf
    owner: root
    group: root
    mode: 0755
  notify:
    - Restart nginx

